<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>05 - Unit Web</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>de5fd00d-c813-4cf3-ac53-63c5bf695151</testSuiteGuid>
   <testCaseLink>
      <guid>159c5e68-99a0-4879-add4-a8995fbfac0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Edit Travel Doc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32e7282-af06-4195-8835-2df5fb3e6696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40206a6d-638b-4ebe-bc7c-f4bba69282ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>975a5f81-2977-4437-a561-e708e3c848df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c7567e-805b-4bf3-a9da-ac96f6126767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb57e04-1cf0-45e8-bef1-9b38beb01212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0644dd65-b6fa-4b66-90a2-a2252e5bcac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db2ee2fa-6906-4c5f-93da-eb0e7150a42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b325094-1de1-4e26-a503-b365284252f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac80cc4c-6a2e-4e73-a9e8-2450fc222ac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a06fdb-545f-4a6a-ac7f-ef43bc3014fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48a5a88-4d59-4171-8723-6698d843039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d54e44e-a9be-44a8-b21d-d9d42a5c6c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14532d0c-65bd-4e15-8010-7b4ebdcdb17f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3719121b-dafe-4f79-b23b-0f056b1a2a00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Edit EmbReg</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32e7282-af06-4195-8835-2df5fb3e6696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40206a6d-638b-4ebe-bc7c-f4bba69282ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>975a5f81-2977-4437-a561-e708e3c848df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c7567e-805b-4bf3-a9da-ac96f6126767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb57e04-1cf0-45e8-bef1-9b38beb01212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0644dd65-b6fa-4b66-90a2-a2252e5bcac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db2ee2fa-6906-4c5f-93da-eb0e7150a42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b325094-1de1-4e26-a503-b365284252f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac80cc4c-6a2e-4e73-a9e8-2450fc222ac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a06fdb-545f-4a6a-ac7f-ef43bc3014fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48a5a88-4d59-4171-8723-6698d843039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d54e44e-a9be-44a8-b21d-d9d42a5c6c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14532d0c-65bd-4e15-8010-7b4ebdcdb17f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe576319-4c64-4faa-aeb5-0f0bf85262d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Edit Printed Photo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22764a56-17ab-4621-ab73-023c072973dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac0dd8a-a26a-4343-abcb-483231519d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2554f3c-ac83-4f29-af47-87fa536bdc1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a96c74e2-2127-485d-bf71-20555f32e8f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Edit PickUp Photo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22764a56-17ab-4621-ab73-023c072973dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac0dd8a-a26a-4343-abcb-483231519d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2554f3c-ac83-4f29-af47-87fa536bdc1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>424355af-5724-4b5b-a1d9-42d6f79e0a6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Edit Digital Photo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22764a56-17ab-4621-ab73-023c072973dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac0dd8a-a26a-4343-abcb-483231519d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2554f3c-ac83-4f29-af47-87fa536bdc1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47882ff7-b69d-4f6c-b746-29521dc72487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Edit Renewal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>da9b29ca-d21d-42c0-a2e0-8ee677719018</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - FileUpload Methods</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7c64b381-da54-48e3-bb38-21826454cf7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Prefill Dropdown</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>aa6da910-eab5-484e-909c-e4acf33a6bcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Upgrade Processing Speed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6dcec877-8e1a-4fd0-83c5-c4b804782e11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Payment - Submitting with PayPal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32e7282-af06-4195-8835-2df5fb3e6696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40206a6d-638b-4ebe-bc7c-f4bba69282ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>975a5f81-2977-4437-a561-e708e3c848df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c7567e-805b-4bf3-a9da-ac96f6126767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb57e04-1cf0-45e8-bef1-9b38beb01212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0644dd65-b6fa-4b66-90a2-a2252e5bcac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db2ee2fa-6906-4c5f-93da-eb0e7150a42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b325094-1de1-4e26-a503-b365284252f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac80cc4c-6a2e-4e73-a9e8-2450fc222ac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a06fdb-545f-4a6a-ac7f-ef43bc3014fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48a5a88-4d59-4171-8723-6698d843039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d54e44e-a9be-44a8-b21d-d9d42a5c6c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14532d0c-65bd-4e15-8010-7b4ebdcdb17f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79080ed5-da8a-4e91-ad7c-6915a2c728c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Payment - Submitting with Amazon</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32e7282-af06-4195-8835-2df5fb3e6696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40206a6d-638b-4ebe-bc7c-f4bba69282ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>975a5f81-2977-4437-a561-e708e3c848df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c7567e-805b-4bf3-a9da-ac96f6126767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb57e04-1cf0-45e8-bef1-9b38beb01212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0644dd65-b6fa-4b66-90a2-a2252e5bcac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db2ee2fa-6906-4c5f-93da-eb0e7150a42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b325094-1de1-4e26-a503-b365284252f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac80cc4c-6a2e-4e73-a9e8-2450fc222ac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a06fdb-545f-4a6a-ac7f-ef43bc3014fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48a5a88-4d59-4171-8723-6698d843039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d54e44e-a9be-44a8-b21d-d9d42a5c6c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14532d0c-65bd-4e15-8010-7b4ebdcdb17f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>505f6c13-5e8e-43d9-9db3-e93d1d63d952</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Automated Scenarios/Unite/Application - Use different currencies</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>85487566-115f-445e-abaa-ab8c6b73dacb</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>6,9,14,17,28,36,41,59,68,121</value>
         </iterationEntity>
         <testDataId>Data Files/Database</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>85487566-115f-445e-abaa-ab8c6b73dacb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SelectCurrency</value>
         <variableId>be7cf933-71c1-453b-a297-d8e857cc2160</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
