<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header - Photos</name>
   <tag></tag>
   <elementGuidId>2b340688-8409-4e35-a90e-a5a954e36ea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_passport_photos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_passport_photos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>912d5a76-d808-41f3-a8e5-b811cb042442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_passport_photos</value>
      <webElementGuid>c4dd8f7d-3b0e-40aa-b9b5-16078eac3b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-link-dropdown-btn px-0 lg:px-4</value>
      <webElementGuid>4d29dc6a-7b0e-4520-a793-db2365eaf880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/photos</value>
      <webElementGuid>c3eb654b-9913-4980-b5c9-411da0956c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Photos    </value>
      <webElementGuid>a8b0cfe7-9d6d-45ae-86b2-5788db6f71ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_passport_photos&quot;)</value>
      <webElementGuid>5d5a2577-cd3c-41ce-9250-dc0abf6994a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_passport_photos']</value>
      <webElementGuid>b16e860d-f8b3-45bd-9436-0c0c8900a1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-header']/nav/ul/li[3]/a</value>
      <webElementGuid>efe2b56a-96c0-43fd-b9ce-5c2bb841d967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Photos')]</value>
      <webElementGuid>d97062bf-df50-4e3c-9deb-d28e6c33e2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passport'])[1]/following::a[1]</value>
      <webElementGuid>9dd6043b-9384-41ac-bde8-b7ddc470e9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel Documents'])[1]/following::a[2]</value>
      <webElementGuid>3c4ce6d3-b8b8-4fb3-aad3-3026d4df3f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[2]</value>
      <webElementGuid>54611183-675b-451a-8bc3-ca2b1937b7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (en)'])[1]/preceding::a[3]</value>
      <webElementGuid>7439dfa3-415e-45c5-9044-f8a1c8d70845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Photos']/parent::*</value>
      <webElementGuid>42f577b7-cb00-496f-a525-cf9feeb35ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/photos')]</value>
      <webElementGuid>07cb53ff-12cd-49c4-980a-416900e1122b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>8a97b68a-d7e1-427e-b96e-aba168e8a50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_passport_photos' and @href = '/photos' and (text() = '
        Photos    ' or . = '
        Photos    ')]</value>
      <webElementGuid>c8ad1b9a-b882-48ce-a80c-1dfea4077db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
