<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - GetStarted Widget</name>
   <tag></tag>
   <elementGuidId>eabad285-a035-4887-af1f-da5463a1fbcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_visa_checker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_visa_checker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>833fb155-3628-40a5-88e3-9a14bb5b6b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--std btn--wide</value>
      <webElementGuid>27864b45-7bfd-4bf1-868e-4634ac488788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_visa_checker</value>
      <webElementGuid>ea8dfccf-4efd-46cb-ae4b-a67afa096e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Started!</value>
      <webElementGuid>442de4f1-1142-42eb-8441-6de4dcfddffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_visa_checker&quot;)</value>
      <webElementGuid>f4d8ea55-d11a-448d-ab82-223e3b16d004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c992b856-175f-46b6-9c88-f0e5bde51011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--std btn--wide</value>
      <webElementGuid>b6ffa208-4ef8-48b4-8755-8bebb19a1c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_visa_checker</value>
      <webElementGuid>e3ab5854-00a2-4b54-a5fa-e08a794eb2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Started!</value>
      <webElementGuid>8f310303-709f-48cb-8c4c-4f02796855fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_visa_checker&quot;)</value>
      <webElementGuid>599a4a8e-4dca-470f-95d0-a49dae586dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_visa_checker']</value>
      <webElementGuid>ee6aa1c1-a470-486f-a384-a10cb7eda481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/form/div[3]/button</value>
      <webElementGuid>75539932-a056-45ad-83dc-6858792d58f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveling to'])[1]/following::button[1]</value>
      <webElementGuid>68c21a13-f8e8-44ed-838f-d3a5418a0857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where am I Going?'])[1]/following::button[1]</value>
      <webElementGuid>ca36328a-f7d8-4b3a-a6fb-b736f0a5994c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>cbc03b0a-823a-4f94-a8d9-22a916124d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_visa_checker' and (text() = 'Get Started!' or . = 'Get Started!')]</value>
      <webElementGuid>79d61acf-5610-4b00-a9e2-787d520c2b62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
