<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Traveling from</name>
   <tag></tag>
   <elementGuidId>db8ca6f9-98bf-4d7a-a0c7-a0c4450e260e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;doNotAutofill0.011657907160598002&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-dusk='Nationality as in Passport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb279aed-6d42-47c1-b787-810a9c499a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doNotAutofill0.011657907160598002</value>
      <webElementGuid>297ef70a-3df8-44ea-8c3c-58c33d25cd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5a9b86bb-01d8-4357-ac13-8f56af58e725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>19c6bd49-d266-408c-b68c-b35a65e5dd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c055538-fc92-4bf5-b127-ba2703f38766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dusk</name>
      <type>Main</type>
      <value>Nationality as in passport</value>
      <webElementGuid>fa24a5a8-208b-448b-adeb-58348ba77252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-2 h-9 pl-8 text-base rounded-md bg-white border-1 border-solid border-gray-300 inputoption__filter nav-link flex items-center focus:outline-none focus:border-green-500</value>
      <webElementGuid>ed900cbc-c368-45b3-af73-31831f63dc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countryFrom&quot;)/div[@class=&quot;dropdown-filter z-50 shadow-lg dropdown-menu w-full relative eraseInside text-gray-500 show&quot;]/input[@class=&quot;m-2 h-9 pl-8 text-base rounded-md bg-white border-1 border-solid border-gray-300 inputoption__filter nav-link flex items-center focus:outline-none focus:border-green-500&quot;]</value>
      <webElementGuid>f571c2d5-38ab-45fa-8c4c-2e7ebf56834e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@data-dusk='Nationality as in passport']</value>
      <webElementGuid>b20a9113-42ce-4107-878f-d3e6b6036e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='countryFrom']/div[2]/input</value>
      <webElementGuid>59762d24-e837-4177-aae4-546a0195b663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>06c4570c-c9fe-4958-a821-3e0f9699bdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@data-dusk='Nationality as in passport' and @type='search']</value>
      <webElementGuid>e400b55a-b170-443e-a255-d6205ee5dc13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
