<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WidQuestion - Traveling to</name>
   <tag></tag>
   <elementGuidId>d8268151-4930-48f3-8413-4a86cb227821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Traveling to']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14f77c92-9eee-425d-ac51-0cb894e8b285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 pr-4 bg-white rounded-md flex items-center h-10 leading-none cursor-pointer focus:outline-none w-full text-base border-1 border-solid border-gray-300 lg:text-xl text-gray-500</value>
      <webElementGuid>624b9eff-b3bd-4f30-8738-d4d377d0e985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flip</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2605d622-fac2-4d4d-979f-debf1362e64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f05e85d-1795-4c0c-8972-acc5faf9fd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c69178a3-9a6d-469e-ac92-3ae00a9bd5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd34ff01-ee4d-49df-9f9e-680145712e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Traveling to</value>
      <webElementGuid>86f9b1c7-9c4d-44b4-8cca-c3592b4eda71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;text-white md:flex md:items-center md:flex-col md:justify-center relative bg-center bg-no-repeat bg-cover homepage-intro lg:mb-16 pt-8 lg:pt-20 md:pt-0 pb-24 lg:pb-12 px-4 w-full h-full&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;w-full max-content mx-auto max-w-container px-2 rounded-md h-full flex flex-col md:flex-row my-0 items-end widget-visa-checker mb-0 flex-col md:flex-row md:py-5&quot;]/div[@class=&quot;m-0 py-0 intro-item md:w-1/2 px-2 h-24 flex flex-col justify-center items-center p-0 md:h-full w-full relative rounded-br-md rounded-bl-md md:rounded-bl-none md:rounded-tr-md&quot;]/div[@class=&quot;dropdown w-full&quot;]/div[@class=&quot;py-2 pr-4 bg-white rounded-md flex items-center h-10 leading-none cursor-pointer focus:outline-none w-full text-base border-1 border-solid border-gray-300 lg:text-xl text-gray-500&quot;]</value>
      <webElementGuid>d653b765-91bb-4446-b445-1408b062d6d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/form/div[2]/div/div</value>
      <webElementGuid>d3a4017b-ed26-4d01-9028-db24933738a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where am I Going?'])[1]/following::div[2]</value>
      <webElementGuid>ca18d17c-7d59-4f8c-a77c-cffe0df89aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States (US)'])[1]/following::div[5]</value>
      <webElementGuid>e8455fe5-08e2-4601-b074-7eb15617f2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started!'])[1]/preceding::div[4]</value>
      <webElementGuid>8835012d-3a3b-46ca-a189-0a2564ae37bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>77638cc5-e30a-423e-a5d6-19a0f4e2a57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Traveling to' or . = 'Traveling to')]</value>
      <webElementGuid>8cafe5dd-c20b-449c-8bee-2281768dc8c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
