<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - ContinueUnderSidebar</name>
   <tag></tag>
   <elementGuidId>acba8f80-3141-4994-9e85-35ef17763a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnContinueSidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnContinueSidebar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37c2f163-1e78-4901-9f65-1eabb7d9614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--std btn--full btnContinue</value>
      <webElementGuid>9e6f8e92-d756-4441-a1c8-a178c8fc78a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinueSidebar</value>
      <webElementGuid>991f255a-c67b-4c17-991f-6c42988b263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b8b8b449-91b1-4eb7-a1a0-58f89d34fe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>229b3365-79ea-4711-893b-9c3fd2fe4953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinueSidebar&quot;)</value>
      <webElementGuid>d79ee1d8-4fae-4536-9d04-d2f36986b2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnContinueSidebar']</value>
      <webElementGuid>d373d259-1cd3-460b-a77f-99ba77e3032f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>138330e8-7966-478c-a76b-be10b59b65ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VND   —   ₫'])[1]/following::button[1]</value>
      <webElementGuid>c5c9a4a7-7b59-4ae2-b8e4-d9f16a46d1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UZS   —   лв'])[1]/following::button[1]</value>
      <webElementGuid>e2631c88-eadd-4992-8843-17b4976ce31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[2]/preceding::button[1]</value>
      <webElementGuid>9135ac65-c578-446b-9b66-dac5dbf9b869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>2211152c-f6a7-4d59-ab5c-02e7f9af6837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnContinueSidebar' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>2f0e97e4-b31b-4810-8694-bc75cd516b71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
