<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - ContinueUnderForm</name>
   <tag></tag>
   <elementGuidId>e46a27d7-09ca-4ba8-a7df-db2b17ff87fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnContinueSidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnContinueUnderSection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8e985ed-cd21-4367-ab47-a6f4fb3b8775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--std btn--full btnContinue</value>
      <webElementGuid>95b49745-f520-4bc4-85a2-6ded26f72a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinueSidebar</value>
      <webElementGuid>c1fdb75b-482a-4f77-9923-0924d15bdaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>06a22236-ac76-4895-b539-98156f4e72dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>131b3970-a978-4a6f-89ed-33ce50ff341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinueSidebar&quot;)</value>
      <webElementGuid>770a06be-e561-4f87-853f-ec0ea44c9370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnContinueUnderSection']</value>
      <webElementGuid>0f2c03dd-79d8-40b2-a415-44bca44ed3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>89b4f91f-203a-4dc4-9e69-4feee1d19c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VND   —   ₫'])[1]/following::button[1]</value>
      <webElementGuid>eb4e68b7-60a3-41c7-ac8a-f2158c8471cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UZS   —   лв'])[1]/following::button[1]</value>
      <webElementGuid>291a7b61-9324-485e-8789-a2c753a1d453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[2]/preceding::button[1]</value>
      <webElementGuid>e85b1708-b10f-452c-a6c9-6753bb1f17eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>0beffb60-2594-4327-8bfb-a2db916d831b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnContinueSidebar' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>b19647e2-d415-49bd-915f-1cd16e3198c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
