<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - CompleteProcess</name>
   <tag></tag>
   <elementGuidId>9e90ff57-abaf-4a91-917b-b768f0f6f7f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCompleteProcess</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnCompleteProcess']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7726a692-5985-4833-a8d0-4e6e06b03942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--std btn--wide capitalize</value>
      <webElementGuid>474a143b-232e-4529-85c6-647b5cccfb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCompleteProcess</value>
      <webElementGuid>9d7c1caf-fc34-42ba-a3c0-256644d4fd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78d38880-fcbe-4471-b35c-7276b66ace43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete Order Process</value>
      <webElementGuid>6475bdec-dc7a-43a8-987d-4392c469f883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCompleteProcess&quot;)</value>
      <webElementGuid>c60f33c3-ea24-4c21-8f1a-8c75ee141d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnCompleteProcess']</value>
      <webElementGuid>e4a33497-2b6a-498f-81a0-3f9330f8b8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paynow']/div/div/div/main/div/div[3]/a/button</value>
      <webElementGuid>988225cb-9821-4c51-bbc5-8fd682220d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One Applicant'])[1]/following::button[1]</value>
      <webElementGuid>6512cea8-32e7-4f0a-a942-a3a582aea9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number Of Applicants'])[1]/following::button[1]</value>
      <webElementGuid>0c404a9a-1934-4af5-89cc-54aff2a549fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/preceding::button[1]</value>
      <webElementGuid>361fbcc3-88d5-4b81-8ac7-d90f31b1bb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/button</value>
      <webElementGuid>e3b1f957-9ad1-4925-a5d5-3c40d320067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnCompleteProcess' and @type = 'button' and (text() = 'Complete Order Process' or . = 'Complete Order Process')]</value>
      <webElementGuid>8a1407c7-51a9-45e3-82ab-58e87a5efb64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
