<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar - Departure Date</name>
   <tag></tag>
   <elementGuidId>8170114a-4b0c-4714-a743-cf4da2e00635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vc-day.id-2022-04-23.day-23.day-from-end-8.weekday-7.weekday-position-6.weekday-ordinal-4.weekday-ordinal-from-end-2.week-4.week-from-end-2.in-month.vc-day-box-center-center > span.vc-day-content.vc-focusable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(), '20')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>602c8e02-19d6-4be3-a335-39cb395a167a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6f5f81f5-de78-45f6-928f-0019e4182543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>sábado, 23 de abril de 2022</value>
      <webElementGuid>648b9ebe-576e-4270-8300-cc6d879a094f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7a971b5-1ce8-4e11-895a-0f61e00bf114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ed5cda9-7f05-4b0c-81fa-443b9e051a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-day-content vc-focusable</value>
      <webElementGuid>05f6c568-4dae-4352-84a8-f1e62081cba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>3b71d939-3728-4610-b1e6-7e0535dee2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-12 sm:mb-0&quot;]/div[1]/div[1]/div[@class=&quot;flex flex-col lg:flex-row items-start&quot;]/div[@class=&quot;w-full mx-auto order-2 lg:order-none lg:w-2/3 xl:w-3/4 lg:pr-8&quot;]/div[2]/div[@class=&quot;mb-4 shadow rounded-md bg-white pb-4 border-gray-300 border-1 border-solid&quot;]/div[@class=&quot;border-gray-100 border-t-2 border-solid w-full md:px-0 pt-5 flex flex-col justify-center&quot;]/div[@class=&quot;card-body px-5&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group flex flex-col justify-end col-12 col-md-8 col-sm-6&quot;]/div[@class=&quot;ivisa-input-wrapper w-full&quot;]/div[@class=&quot;w-full +&quot;]/div[1]/div[1]/div[@class=&quot;vc-popover-content-wrapper is-interactive&quot;]/div[@class=&quot;vc-popover-content direction-bottom vc-container&quot;]/div[@class=&quot;vc-container vc-blue&quot;]/div[@class=&quot;vc-pane-container&quot;]/div[@class=&quot;vc-pane-layout&quot;]/div[@class=&quot;vc-pane row-from-end-1 column-from-end-1&quot;]/div[@class=&quot;vc-weeks&quot;]/div[@class=&quot;vc-day id-2022-04-23 day-23 day-from-end-8 weekday-7 weekday-position-6 weekday-ordinal-4 weekday-ordinal-from-end-2 week-4 week-from-end-2 in-month vc-day-box-center-center&quot;]/span[@class=&quot;vc-day-content vc-focusable&quot;]</value>
      <webElementGuid>db1f1bdd-a608-41ee-ad85-38d0c96dea27</webElementGuid>
   </webElementProperties>
</WebElementEntity>
