<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID 3 - departure_date.general</name>
   <tag></tag>
   <elementGuidId>54e85d1d-f6bf-4535-af90-43ff57db1e5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;general.departure_date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='general.departure_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7a60d30-1753-4852-a83e-4966b534a529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control q-select</value>
      <webElementGuid>31aa112a-535c-43ba-a9f0-4091c16a0514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date</value>
      <webElementGuid>df750da4-587e-465e-83dc-4f79c2ef5124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>general.departure_date</value>
      <webElementGuid>292bea18-845c-4148-aa88-797cf1dfbaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-12 sm:mb-0&quot;]/div[1]/div[1]/div[@class=&quot;flex flex-col lg:flex-row items-start&quot;]/div[@class=&quot;w-full mx-auto order-2 lg:order-none lg:w-2/3 xl:w-3/4 lg:pr-8&quot;]/div[2]/div[@class=&quot;mb-4 shadow rounded-md bg-white pb-4 border-gray-300 border-1 border-solid&quot;]/div[@class=&quot;border-gray-100 border-t-2 border-solid w-full md:px-0 pt-5 flex flex-col justify-center&quot;]/div[@class=&quot;card-body px-5&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group flex flex-col justify-end col-12 col-md-8 col-sm-6&quot;]/div[@class=&quot;ivisa-input-wrapper w-full&quot;]/div[@class=&quot;w-full +&quot;]/div[1]/div[1]/div[@class=&quot;flex items-center&quot;]/input[@class=&quot;form-control q-select&quot;]</value>
      <webElementGuid>25da554d-9fa6-4d9f-ac64-2f9500483333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='general.departure_date']</value>
      <webElementGuid>43dfe792-5d75-4f15-ad1e-9e087b309721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>dc8f8779-0731-47a9-982d-62e5939d7de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>f98eab63-b295-4f30-9606-9782e49b527d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Select Date' and @name = 'general.departure_date']</value>
      <webElementGuid>4ff29131-7393-4afe-83e0-6bd681066412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
