<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID 7 - nationality_country (A2)</name>
   <tag></tag>
   <elementGuidId>367bd22e-5de6-407f-8072-00f2e1c8cfff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;applicant.1.nationality_country&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='applicant.1.nationality_country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c1a27460-089d-4998-a6f2-e9c038c8e4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ivisa-form-field ivisa-input-dropdown form-control</value>
      <webElementGuid>78bfb073-676d-47d3-85c6-d6621c4bd63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicant.1.nationality_country</value>
      <webElementGuid>c76d2259-9a5b-41d4-b0d9-66bf39167036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AustraliaAustriaCanadaFinlandIndiaIrelandItalyMaldivesMexicoMonacoNetherlandsNew ZealandSpainUnited KingdomUnited States</value>
      <webElementGuid>4a5ffe51-bc8e-40d8-8fac-ccd7ad60f0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-12 sm:mb-0&quot;]/div[1]/div[1]/div[@class=&quot;flex flex-col lg:flex-row items-start&quot;]/div[@class=&quot;w-full mx-auto order-2 lg:order-none lg:w-2/3 xl:w-3/4 lg:pr-8&quot;]/div[2]/div[@class=&quot;mb-4 shadow rounded-md bg-white pb-4 border-gray-300 border-1 border-solid&quot;]/div[@class=&quot;border-gray-100 border-t-2 border-solid w-full md:px-0 pt-5&quot;]/div[@class=&quot;card-body px-5&quot;]/div[@class=&quot;form-row flex flex-col lg:flex-row&quot;]/div[@class=&quot;form-group flex flex-col justify-end max-w-full col-12 col-md-8&quot;]/div[@class=&quot;ivisa-input-wrapper w-full&quot;]/div[@class=&quot;w-full +&quot;]/div[1]/select[@class=&quot;ivisa-form-field ivisa-input-dropdown form-control&quot;]</value>
      <webElementGuid>4f7c4093-4d0d-4290-913d-0f6560a9f1fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='applicant.1.nationality_country']</value>
      <webElementGuid>2bf9ec07-60fa-44cc-93e5-b69af7578369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div[2]/div[3]/div[2]/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>5035c0a1-69b5-40b7-b975-557eabd0dd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality (as in Passport)'])[2]/following::select[1]</value>
      <webElementGuid>1c8802c2-5437-4d8d-b61d-a74c45cb573f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>32b4da48-382a-4f86-bff9-f7c80d3ce52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'applicant.1.nationality_country' and (text() = 'AustraliaAustriaCanadaFinlandIndiaIrelandItalyMaldivesMexicoMonacoNetherlandsNew ZealandSpainUnited KingdomUnited States' or . = 'AustraliaAustriaCanadaFinlandIndiaIrelandItalyMaldivesMexicoMonacoNetherlandsNew ZealandSpainUnited KingdomUnited States')]</value>
      <webElementGuid>c6865849-e9f9-488d-b798-d31be2dc5eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
