<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID 98 - port_of_arrival.general</name>
   <tag></tag>
   <elementGuidId>1b723cdd-bfa2-4838-bc38-e01f571efc32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;general.port_of_arrival&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='general.port_of_arrival']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eeab3b70-f266-4923-bbd8-7e1f9af6f1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ivisa-form-field ivisa-input-dropdown form-control</value>
      <webElementGuid>8a00d21a-aaf9-4a43-9255-3287fea93fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>general.port_of_arrival</value>
      <webElementGuid>3088d929-caab-4b93-932a-06755faa4771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ahmedabad AirportAmritsar AirportBagdogra AirportBengaluru AirportCalicut (Kozhikode) AirportChandigarh AirportChennai AirportChennai SeaportCochin AirportCochin SeaportCoimbatore AirportDelhi Airport (Most common)Gaya AirportGoa AirportGoa SeaportGuwahati AirportHyderabad AirportJaipur AirportKolkata AirportLucknow AirportMadurai AirportMangalore AirportMangalore SeaportMumbai AirportMumbai SeaportNagpur AirportPune AirportTiruchirapalli AirportTrivandrum AirportVaranasi AirportVishakhapatnam (Vizag)Bhubaneshwar AirportPortBlair AirportOther</value>
      <webElementGuid>a3248d96-c656-455d-8d08-58b18930feb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-12 sm:mb-0&quot;]/div[1]/div[1]/div[@class=&quot;flex flex-col lg:flex-row items-start&quot;]/div[@class=&quot;w-full mx-auto order-2 lg:order-none lg:w-2/3 xl:w-3/4 lg:pr-8&quot;]/div[2]/div[@class=&quot;mb-4 shadow rounded-md bg-white pb-4 border-gray-300 border-1 border-solid&quot;]/div[@class=&quot;border-gray-100 border-t-2 border-solid w-full md:px-0 pt-5 flex flex-col justify-center&quot;]/div[@class=&quot;card-body px-5&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group flex flex-col justify-end col-12 col-md-8 col-sm-5&quot;]/div[@class=&quot;ivisa-input-wrapper w-full&quot;]/div[@class=&quot;w-full +&quot;]/div[1]/select[@class=&quot;ivisa-form-field ivisa-input-dropdown form-control&quot;]</value>
      <webElementGuid>77c02cca-bb68-406d-8ce2-a1935a00219e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='general.port_of_arrival']</value>
      <webElementGuid>b72c0703-259f-40a8-93c2-f044705dda4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>f78e9dad-21fa-4bb5-8973-bb2f04fd601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Port of Arrival'])[1]/following::select[1]</value>
      <webElementGuid>97645a34-a1a4-4d36-bdf0-e6b732a24aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated End of Trip'])[1]/following::select[1]</value>
      <webElementGuid>0db705fe-1020-4fe5-8078-e329c1a6abd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/preceding::select[1]</value>
      <webElementGuid>d69b0784-2c42-42fd-9c93-157aef03245d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::select[1]</value>
      <webElementGuid>d574f87c-25be-4932-bdcd-7d4dbcb66df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cf2806c7-f8c4-4cb9-bfd6-73bb03c5b1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'general.port_of_arrival' and (text() = 'Ahmedabad AirportAmritsar AirportBagdogra AirportBengaluru AirportCalicut (Kozhikode) AirportChandigarh AirportChennai AirportChennai SeaportCochin AirportCochin SeaportCoimbatore AirportDelhi Airport (Most common)Gaya AirportGoa AirportGoa SeaportGuwahati AirportHyderabad AirportJaipur AirportKolkata AirportLucknow AirportMadurai AirportMangalore AirportMangalore SeaportMumbai AirportMumbai SeaportNagpur AirportPune AirportTiruchirapalli AirportTrivandrum AirportVaranasi AirportVishakhapatnam (Vizag)Bhubaneshwar AirportPortBlair AirportOther' or . = 'Ahmedabad AirportAmritsar AirportBagdogra AirportBengaluru AirportCalicut (Kozhikode) AirportChandigarh AirportChennai AirportChennai SeaportCochin AirportCochin SeaportCoimbatore AirportDelhi Airport (Most common)Gaya AirportGoa AirportGoa SeaportGuwahati AirportHyderabad AirportJaipur AirportKolkata AirportLucknow AirportMadurai AirportMangalore AirportMangalore SeaportMumbai AirportMumbai SeaportNagpur AirportPune AirportTiruchirapalli AirportTrivandrum AirportVaranasi AirportVishakhapatnam (Vizag)Bhubaneshwar AirportPortBlair AirportOther')]</value>
      <webElementGuid>6105d5d9-585e-4e3d-8d6e-d0eb12db8d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
