<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID 904 - common_nationality_country.general</name>
   <tag></tag>
   <elementGuidId>2729f160-2726-49c1-9906-a30666c6932c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;general.common_nationality_country&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='general.common_nationality_country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f48707ee-06e3-41bc-a934-f850dedc1ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ivisa-form-field ivisa-input-dropdown form-control</value>
      <webElementGuid>74812ba2-09ca-4c06-b6fa-06591f834494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>general.common_nationality_country</value>
      <webElementGuid>3f9e9f0d-debe-4a1c-a9da-a75a91580633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AfghanistanAland IslandsAlbaniaAmerican SamoaAndorraAnguillaAntarcticaAntigua &amp; BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBermudaBhutanBoliviaBonaire, St Eustatius and SabaBosnia and HerzegovinaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaCambodiaCanadaCayman IslandsChileChinaChristmas IslandCocos (K) IslandColombiaCook IslandsCosta RicaCroatiaCubaCuracaoCyprusCzech RepublicDenmarkDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEstoniaFalkland Islands (Malvinas)Faroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench West IndiesGeorgiaGermanyGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuyanaHaitiHeard Island and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsle of ManIsraelItalyJamaicaJapanJerseyJordanKazakhstanKiribatiKosovoKuwaitKyrgyzstanLaosLatviaLebanonLiechtensteinLithuaniaLuxembourgMacaoMacedoniaMalaysiaMaldivesMaltaMarshall IslandsMartiniqueMayotteMexicoMoldovaMonacoMongoliaMontenegroMontserratMyanmarNauruNepalNetherlandsNew CaledoniaNew ZealandNicaraguaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPalestinePanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPortugalPuerto RicoQatarReunionRomaniaRussiaSaint BarthelemySaint HelenaSaint Kitts and NevisSaint LuciaSaint MartinSaint Pierre and MiquelonSaint Vincent &amp; GrenadinesSamoaSan MarinoSaudi ArabiaSerbiaSingaporeSint MaartenSlovakiaSloveniaSolomon IslandsSouth Georgia and the South Sandwich IslandsSouth KoreaSpainSri LankaSurinameSvalbard &amp; Jan MayenSwedenSwitzerlandSyriaTaiwanTajikistanThailandTokelauTongaTrinidad and TobagoTurkeyTurkmenistanTurks &amp; Caicos IslandsTuvaluUK Virgin IslandsUkraineUnited Arab EmiratesUnited KingdomUnited StatesUnited States Minor Outlying IslandsUruguayUS Virgin IslandsUzbekistanVanuatuVatican CityVenezuelaVietnamWallis and FutunaWestern SaharaYemen</value>
      <webElementGuid>947e3abb-f20b-4340-a3b0-9343ecb4c928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-12 sm:mb-0&quot;]/div[1]/div[1]/div[@class=&quot;flex flex-col lg:flex-row items-start&quot;]/div[@class=&quot;w-full mx-auto order-2 lg:order-none&quot;]/div[1]/div[@class=&quot;mb-4 shadow rounded-md bg-white pb-4 border-gray-300 border-1 border-solid&quot;]/div[@class=&quot;border-gray-100 border-t-2 border-solid w-full md:px-0 pt-5 flex flex-col justify-center&quot;]/div[@class=&quot;card-body px-5&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group flex flex-col justify-end col-12 col-md-6&quot;]/div[@class=&quot;ivisa-input-wrapper w-full&quot;]/div[@class=&quot;w-full +&quot;]/div[1]/select[@class=&quot;ivisa-form-field ivisa-input-dropdown form-control&quot;]</value>
      <webElementGuid>0eadb448-8c34-4875-bd1f-7ce1e71802ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='general.common_nationality_country']</value>
      <webElementGuid>d095eb51-ee04-46ef-8d33-6b0d8104c5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/div/select</value>
      <webElementGuid>b5133a7c-06b0-4675-bdd4-6a866d4d9e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where am I from?'])[1]/following::select[1]</value>
      <webElementGuid>4a130bfa-ad62-41e7-afce-2a6a1e9546c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Your Application'])[1]/following::select[1]</value>
      <webElementGuid>2d11ff16-3930-4905-9587-d2cad4d2257f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applying for'])[1]/preceding::select[1]</value>
      <webElementGuid>c1f717ce-d616-4bdd-8f1c-cd40b43b1f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::select[2]</value>
      <webElementGuid>2a929461-81bd-411b-b45f-398a297f1f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c83dfce3-4dad-4bf0-bcb3-1fe36c58c291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'general.common_nationality_country' and (text() = 'AfghanistanAland IslandsAlbaniaAmerican SamoaAndorraAnguillaAntarcticaAntigua &amp; BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBermudaBhutanBoliviaBonaire, St Eustatius and SabaBosnia and HerzegovinaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaCambodiaCanadaCayman IslandsChileChinaChristmas IslandCocos (K) IslandColombiaCook IslandsCosta RicaCroatiaCubaCuracaoCyprusCzech RepublicDenmarkDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEstoniaFalkland Islands (Malvinas)Faroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench West IndiesGeorgiaGermanyGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuyanaHaitiHeard Island and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsle of ManIsraelItalyJamaicaJapanJerseyJordanKazakhstanKiribatiKosovoKuwaitKyrgyzstanLaosLatviaLebanonLiechtensteinLithuaniaLuxembourgMacaoMacedoniaMalaysiaMaldivesMaltaMarshall IslandsMartiniqueMayotteMexicoMoldovaMonacoMongoliaMontenegroMontserratMyanmarNauruNepalNetherlandsNew CaledoniaNew ZealandNicaraguaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPalestinePanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPortugalPuerto RicoQatarReunionRomaniaRussiaSaint BarthelemySaint HelenaSaint Kitts and NevisSaint LuciaSaint MartinSaint Pierre and MiquelonSaint Vincent &amp; GrenadinesSamoaSan MarinoSaudi ArabiaSerbiaSingaporeSint MaartenSlovakiaSloveniaSolomon IslandsSouth Georgia and the South Sandwich IslandsSouth KoreaSpainSri LankaSurinameSvalbard &amp; Jan MayenSwedenSwitzerlandSyriaTaiwanTajikistanThailandTokelauTongaTrinidad and TobagoTurkeyTurkmenistanTurks &amp; Caicos IslandsTuvaluUK Virgin IslandsUkraineUnited Arab EmiratesUnited KingdomUnited StatesUnited States Minor Outlying IslandsUruguayUS Virgin IslandsUzbekistanVanuatuVatican CityVenezuelaVietnamWallis and FutunaWestern SaharaYemen' or . = 'AfghanistanAland IslandsAlbaniaAmerican SamoaAndorraAnguillaAntarcticaAntigua &amp; BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBermudaBhutanBoliviaBonaire, St Eustatius and SabaBosnia and HerzegovinaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaCambodiaCanadaCayman IslandsChileChinaChristmas IslandCocos (K) IslandColombiaCook IslandsCosta RicaCroatiaCubaCuracaoCyprusCzech RepublicDenmarkDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEstoniaFalkland Islands (Malvinas)Faroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench West IndiesGeorgiaGermanyGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuyanaHaitiHeard Island and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsle of ManIsraelItalyJamaicaJapanJerseyJordanKazakhstanKiribatiKosovoKuwaitKyrgyzstanLaosLatviaLebanonLiechtensteinLithuaniaLuxembourgMacaoMacedoniaMalaysiaMaldivesMaltaMarshall IslandsMartiniqueMayotteMexicoMoldovaMonacoMongoliaMontenegroMontserratMyanmarNauruNepalNetherlandsNew CaledoniaNew ZealandNicaraguaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPalestinePanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPortugalPuerto RicoQatarReunionRomaniaRussiaSaint BarthelemySaint HelenaSaint Kitts and NevisSaint LuciaSaint MartinSaint Pierre and MiquelonSaint Vincent &amp; GrenadinesSamoaSan MarinoSaudi ArabiaSerbiaSingaporeSint MaartenSlovakiaSloveniaSolomon IslandsSouth Georgia and the South Sandwich IslandsSouth KoreaSpainSri LankaSurinameSvalbard &amp; Jan MayenSwedenSwitzerlandSyriaTaiwanTajikistanThailandTokelauTongaTrinidad and TobagoTurkeyTurkmenistanTurks &amp; Caicos IslandsTuvaluUK Virgin IslandsUkraineUnited Arab EmiratesUnited KingdomUnited StatesUnited States Minor Outlying IslandsUruguayUS Virgin IslandsUzbekistanVanuatuVatican CityVenezuelaVietnamWallis and FutunaWestern SaharaYemen')]</value>
      <webElementGuid>878003ad-7415-4b5e-a42f-92cfcbf08d94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
