<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reprocess - Responsible</name>
   <tag></tag>
   <elementGuidId>9a71f515-4a0b-409d-bd3b-d229bdcb5d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class='form-control'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;order-item-editor-vue-wrapper&quot;]/div[9]/div/div/main/div[2]/div[2]/select</value>
      <webElementGuid>01bf2680-07d2-4583-b9a7-ce7fa0293db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;order-item-editor-vue-wrapper&quot;]/div[12]/div/div/main/div[2]/div[2]/select</value>
      <webElementGuid>c543bc7a-5cf9-48b3-9e4e-a19565e9dacf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
